name: Release
on:
  push:
    branches:
      - master
jobs:
  release-please:
    name: Prepare Release notes
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release-please.outputs.release_created }}
      pr_number: ${{ steps.echo-pr.outputs.pr_number }}
    steps:
      - id: release-please
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: node
          package-name: jarvis-sdk-web
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
      - uses: actions/checkout@v2
        if: ${{ steps.release-please.outputs.release_created }}
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release-please.outputs.release_created }}
      - run: npm install
        if: ${{ steps.release-please.outputs.release_created }}
      - name: "Build the dist package"
        run: npm run-script build
        if: ${{ steps.release-please.outputs.release_created }}
      - name: "Verify es support of dist package"
        run: npm run-script check-es
        if: ${{ steps.release-please.outputs.release_created }}
      - name: "Publish the package"
        if: ${{ steps.release-please.outputs.release_created }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install CU tool
        if: ${{ steps.release-please.outputs.release_created }}
        run: npm install -g clickup-simple-cli
      - name: Get Version
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          export VERSION=$(cat package.json | jq -r '.version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create CU task
        if: ${{ steps.release-please.outputs.release_created }}
        env:
          CU_list: "186335199"
          CU_token: ${{ secrets.CLICKUPPAT }}
          APP_NAME: "Web UI SDK"
          APP_TAG: "jarvis-sdk-web"
          CU_status: "DEPLOYED"
        run: |
          CU_tags="$APP_TAG,$VERSION,public" cu-cli create -d "Release of $APP_NAME available here: https://www.npmjs.com/package/@indykiteone/$APP_TAG/v/$VERSION" "$APP_NAME - release $VERSION"
      - name: Checkout Release Repo
        uses: actions/checkout@v3
        with:
          repository: indykite/changelog-publisher
          ref: v0.1.0
          path: changelog-publisher
        if: ${{ steps.release-please.outputs.release_created }}
      - name: Run script
        id: run-script
        run: |
          bash parse_changelog.sh -f CHANGELOG.md
        if: ${{ steps.release-please.outputs.release_created }}
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: electron
          record: false
        env:
          CYPRESS_EMAIL: ${{ secrets.RIOT_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.RIOT_PASSWORD }}
          CYPRESS_URL_LOGIN: "https://buildtoriot-dev.web.app/login"
          CYPRESS_URL_TOPIC: "https://buildtoriot-dev.web.app/forum/topic/376"
          CYPRESS_ADD_LINK: true
        if: ${{ steps.release-please.outputs.release_created }}
